
const All_products=[
    
    {
        "id":"o1",
        "product_name":"OnePlus 12",
        "product_detail":"Snapdragon 8 Gen 3",
        "img":"one12.webp",
        "price":64000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o2",
        "product_name":"OnePlus 11",
        "product_detail":"Snapdragon 8 Gen 2",
        "img":"one11.webp",
        "price":56650,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o4",
        "product_name":"OnePlus 9 Pro",
        "product_detail":"Snapdragon 888",
        "img":"one9P.webp",
        "price":184000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o5",
        "product_name":"OnePlus 12R",
        "product_detail":"Snapdragon 8 Gen 2",
        "img":"one12R.webp",
        "price":39890,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o6",
        "product_name":"OnePlus 11R",
        "product_detail":"Snapdragon 8 Plus Gen 1",
        "img":"one11R.webp",
        "price":37900,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o7",
        "product_name":"OnePlus 10 Pro",
        "product_detail":"Snapdragon 8 Gen 1",
        "img":"one10P.webp",
        "price":43190,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"o8",
        "product_name":"OnePlus 10R 5G",
        "product_detail":"MediaTek Dimensity 810",
        "img":"one10R5G.webp",
        "price":34000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },    {
        "id":"a1",
        "product_name":"iPhone 15 pro max",
        "product_detail":"The camera killer iPhone",
        "img":"ip15pm.webp",
        "price":180000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"a2",
        "product_name":"iPhone 15 pro",
        "product_detail":"The ultimate iPhone ",
        "img":"ip15p.jpg",
        "price":134900,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a3",
        "product_name":"iPhone 15",
        "product_detail":"A total powerhouse",
        "img":"ip15.jpg",
        "price":72999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a4",
        "product_name":"iPhone 14 pro max",
        "product_detail":"An Interactive User Experience",
        "img":"ip14pm.webp",
        "price":184000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a5",
        "product_name":"iPhone 14 pro",
        "product_detail":"Dynamic island,an excellent experience",
        "img":"ip14p.webp",
        "price":129000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a6",
        "product_name":"iPhone 14",
        "product_detail":"Ceramic shield is durable by design",
        "img":"ip14.webp",
        "price":64000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a7",
        "product_name":"iPhone 13 pro max",
        "product_detail":"Cinematic mode make video next level",
        "img":"ip13pm.webp",
        "price":129000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a8",
        "product_name":"iPhone 13 pro",
        "product_detail":"TrueDepth camera in Cinematic mode.",
        "img":"ip13p.jpg",
        "price":129000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a9",
        "product_name":"iPhone 13",
        "product_detail":"Crisp and Vivid Display",
        "img":"ip13.webp",
        "price":53000,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"a10",
        "product_name":"iPhone SE",
        "product_detail":"Small but smart",
        "img":"ipSE.webp",
        "price":43900,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false

    },
    {
        "id":"s1",
        "product_name":"Samsung Galaxy S24 Ultra",
        "product_detail":"Snapdragon 8 Gen 3",
        "img":"samS24U.webp",
        "price":112500,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s2",
        "product_name":"Samsung S23 5G",
        "product_detail":"Snapdragon 8 Gen 2",
        "img":"samS235G.webp",
        "price":50990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s3",
        "product_name":"Samsung S23 Ultra 5G",
        "product_detail":"Snapdragon 8 Gen 2",
        "img":"samS23U5G.webp",
        "price":89990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s4",
        "product_name":"Samsung S24 5G",
        "product_detail":"Samsung Exynos 2400",
        "img":"samS245G.webp",
        "price":66990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s5",
        "product_name":"Samsung S22 Ultra",
        "product_detail":"Snapdragon 8 Gen 1",
        "img":"samS22U.webp",
        "price":84999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s6",
        "product_name":"Samsung S24 Plus 5G",
        "product_detail":"Samsung Exynos 2400",
        "img":"samS24P5G.webp",
        "price":99999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s7",
        "product_name":"Samsung Galaxy A54 5G",
        "product_detail":"Samsung Exynos 1380",
        "img":"samGA545G.webp",
        "price":35490,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s8",
        "product_name":"Samsung Galaxy S23 FE",
        "product_detail":"Samsung Exynos 2200",
        "img":"samGS23FE.webp",
        "price":43360,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s9",
        "product_name":"Samsung Galaxy S22 Plus",
        "product_detail":"Snapdragon 8 Gen 1",
        "img":"samGS22P.webp",
        "price":42990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"s10",
        "product_name":"Samsung Z Fold 3",
        "product_detail":"Snapdragon 888",
        "img":"samZF3.webp",
        "price":49999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x1",
        "product_name":"Xiaomi 12 pro",
        "product_detail":"Snapdragon 8 Gen 1",
        "img":"xia12p.webp",
        "price":84999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x2",
        "product_name":"Xiaomi 14 Ultra",
        "product_detail":"Snapdragon 8 Gen 3",
        "img":"xia14U.webp",
        "price":74900,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x3",
        "product_name":"Xiaomi 13T Pro 5G",
        "product_detail":"MediaTek Dimensity 9200",
        "img":"xia13TP5G.webp",
        "price":70490,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x4",
        "product_name":"Xiaomi 13T",
        "product_detail":"MediaTek Dimensity 820",
        "img":"xia13T.webp",
        "price":57990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x5",
        "product_name":"Xiaomi Mix Fold 3",
        "product_detail":"Snapdragon 8 Gen 2",
        "img":"xiaMF3.webp",
        "price":103900,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x6",
        "product_name":"Xiaomi Redmi Note 13 Pro Plus",
        "product_detail":"MediaTek Dimensity 720",
        "img":"xiaRedN13PP.webp",
        "price":30090,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x7",
        "product_name":"Xiaomi 12 Pro 5G",
        "product_detail":"Snapdragon 8 Gen 1",
        "img":"xia12P5G.webp",
        "price":39990,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    },
    {
        "id":"x8",
        "product_name":"Xiaomi Mi 11T Pro 5G",
        "product_detail":"Snapdragon 888",
        "img":"xiaMi11TP5G.webp",
        "price":41999,
        "quantity":1,
        "ram":"8GB",
        "battery":"4000 maH",
        "camera":"12MP+48MP",
        "processor":"Snapdragon 8th gen",
        "added":false
    }
];

export default All_products;